### ISSUE TITLE
線の太さを調整可能にしたい

### ISSUE THREAD

**Issue by noir-neo** [one-night-game-jam/sun-ma#54]
iPhoneXS だとジャギー目立つし svg 検証したいっすね

**Comment by maku693** [comment]
同意。iPadでもジャギってる。

**Comment by noir-neo** [comment]
とりあえず sprite renderer と canvas で問題なく表示できるのを確認した!
大きくしてもキレイ!
![image from ios](https://user-images.githubusercontent.com/3272594/46919826-171b5c00-d020-11e8-976d-ea7fa8ddc1de.jpg)

あと、ざわちゃんイラストレーターでグローどうやって入れてるんだろ。

ただまあ線の太さはまあできたらちょっとうれしいくらいだし、
ジャギってるのは普通に画像大きくしてもまだまだ問題ないサイズだと思うので、手っ取り早くそういう解決でも良い気がした!

**Comment by maku693** [comment]
うーん、単に画像デカく出す方が楽だよね。

技術的にはSVG+グローシェーダってイケてると思うけど、費用対効果悪い気はするね。

この先も2DやってくならSVGはどこかで知見貯めときたいみたいなのはあるけど、やりたければ個人でやればいっか。

**Comment by noir-neo** [comment]
そそ、費用対効果は良くないなって。

まあシュッとやってみてもいいけどねー
グローシェーダ、書く?

**Comment by maku693** [comment]
うーん、パッとできるほど知識ないのでどうしようかな。ちょっと時間かけてもいいならやってみたい気持ちはあるけど、

> やりたければ個人でやればいっか

です。

**Comment by noir-neo** [comment]
んじゃ、とりあえずリリースは画像でかくして、もし時間使うなら別のブラッシュアップしよう
