### ISSUE TITLE
store 用のテキストとか

### ISSUE THREAD

**Issue by noir-neo** [one-night-game-jam/sun-ma#59]
https://developer.apple.com/jp/app-store/product-page/

## 名前
sun-ma

## サブタイトル
The sun grilled Pacific saury
宇宙のサンマ焼きゲーム

## プロモーション用テキスト 
(プロモーション用テキストを使用すると、更新内容を提出することなく、App Store の訪問者に現在の App の機能について知らせることができます。このテキストは、iOS 11 以降および 
macOS 10.13 以降を搭載した端末を使用するカスタマーに対して、App Store の説明の上に表示されます。)

とりあえずなしでいいとおもってる

## 概要 
(特長や機能の詳細など、App に関する説明です。Apple Watch App でも使用されます。)

Launch Pacific sauries, sanma, grill over the sun and serve the dish!

sun-ma is a space action game.
Your mission is simple. Pull and launch Pacific sauries, dock with the dish.
The sun has gravity.
You can bake it quickly near the sun or cook slowly from far away.
Serve more delicious Pacific sauries within a certain time.

サンマを発射、太陽の熱でおいしく焼き上げ、お皿に盛り付けよう！

sun-ma は宇宙を舞台にしたアクションゲームです。
ミッションは単純。サンマをひっぱって射出、お皿とドッキングせよ。
太陽は重力でサンマを引き寄せつつ、その熱でサンマを焼き上げます。
高火力で一気に焼き上げるもよし、低温調理でじっくり火を通すもよし。
時間内により多くのおいしいサンマを届けよう。

## キーワード 
(Appについて説明するキーワードを1つ以上含めてください。キーワードを使用すると、App Storeでより正確な検索結果が表示されます。各キーワードは半角カンマ、全角カンマ、またはその両方を使用して区切ってください。)
sunma,sanma,summa,samma,pacific saury,saury,fish,sun,slingshot
sunma,sanma,summa,samma,san-ma,秋刀魚,さんま,サンマ,さかな,魚,太陽,スリングショット

**Comment by maku693** [comment]
「sun-ma は宇宙の物理ベースゲームです。」は削ってもいい気がしている。
物理ベースとは 🤔 ❓ というところと、物理を有効活用している感をそこまで押し出したいのか（実際いわゆる物理のバグ的な面白さはない）が気になる。

わざとならそのままでいいけど、なにかタグライン的なものが欲しければ、たとえば

sun-ma は宇宙を舞台にしたアーケードスタイルのアクションゲームです。
sun-ma is an arcade-style action game set in space.

とかどうだろう（アクションゲームではないのではという意見はあると思う）。

**Comment by maku693** [comment]
あとめちゃこまかいけどランデブーだとドッキングまではいかない距離の感じがしてしまう。

**Comment by noir-neo** [comment]
なるほどね
しかしアーケードってこういうことなのか…？(よくわかってない
アクションというのは無しではないと思ってた
とりあえず意図としてはタグラインって書いてくれてるけど、一言でゲームジャンル言いたかったってことで合ってて、
宇宙を舞台にしたアクションゲーム、くらいにしておくかね

ランデブーそうなんだよねー 厳密には！
とりあえず宇宙っぽい単語使いたかっただけなんだが…
ランディングとかドッキングもちょっと違うよねー
